### ISSUE TITLE
panic while giving illegal regex

### ISSUE THREAD

**Issue by shenjackyuanjie** [spyoungtech/regexrs#11]
```
  File "./ica-rs/plugins/bmcl.py", line 238, in bmcl_rank
    pattern = regexrs.compile(name)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    *.
    ^
error: repetition operator missing expression
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)

```

**Comment by shenjackyuanjie** [comment]
you should add some match for it

**Comment by spyoungtech** [comment]
Thanks for the report. As I understand it, an exception is the expected behavior in this case (as is what occurs when an illegal regex is provided to the stdlib `re.compile`).

```py
import re
re.compile('*.')  # error: nothing to repeat at position 0
```

Though, maybe we could probably make the error message better instead of letting the panic bubble up.

**Comment by shenjackyuanjie** [comment]
yes, the problem is you can just raise an error, but not panic, and let pyo3 raise it's error

**Comment by shenjackyuanjie** [comment]
looks nice, thanks!
